"""
InteractiveWebRenderer - 交互式网页渲染器
将 MVM 解析结果渲染为带交互能力的完整 HTML 页面
所有交互逻辑由渲染器注入，.mvm 文件本身不包含任何 JavaScript
"""

import html
from ..data_object import DataObject
from ..renderers import BaseRenderer


class InteractiveWebRenderer(BaseRenderer):
    def file_extension(self) -> str:
        return "html"

    def render(self, result, dark: bool = False) -> str:
        data = result.data
        title = data.get("title", "MVM Document")
        subtitle = data.get("subtitle", "")
        author = data.get("author", "")
        date = data.get("date", "")
        tags = data.get("tags", [])
        sections = data.get("sections", [])

        sections_html = self._render_sections(sections)

        tags_html = " ".join(
            f'<span class="tag">{html.escape(t)}</span>' for t in tags
        )

        toc_html = self._build_toc(sections)

        dark_class = "dark" if dark else ""

        return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(title)}</title>
<style>
{self._get_css(dark)}
</style>
</head>
<body class="{dark_class}">
<div class="layout">
  <aside class="sidebar" id="sidebar">
    <div class="sidebar-header">
      <span class="logo">MVM</span>
      <button class="sidebar-close" onclick="document.getElementById('sidebar').classList.remove('open')" aria-label="Close">&times;</button>
    </div>
    <nav class="toc" id="toc">
      {toc_html}
    </nav>
    <div class="sidebar-footer">
      <button class="theme-toggle" onclick="toggleTheme()" title="Toggle theme">
        <span class="theme-icon" id="themeIcon">&#9790;</span>
      </button>
      <button class="fullscreen-btn" onclick="toggleFullscreen()" title="Fullscreen">&#x26F6;</button>
    </div>
  </aside>
  <main class="content" id="content">
    <div class="toolbar">
      <button class="menu-btn" onclick="document.getElementById('sidebar').classList.add('open')" aria-label="Menu">&#9776;</button>
      <div class="search-box">
        <input type="text" id="searchInput" placeholder="Search sections..." oninput="filterSections(this.value)">
      </div>
      <div class="progress-bar"><div class="progress-fill" id="progressFill"></div></div>
    </div>
    <div class="container">
      <div class="header">
        <h1>{html.escape(title)}</h1>
        {f'<div class="subtitle">{html.escape(subtitle)}</div>' if subtitle else ''}
        <div class="meta">
          {f'<span>{html.escape(author)}</span>' if author else ''}
          {f'<span>{html.escape(date)}</span>' if date else ''}
        </div>
        {f'<div class="tags">{tags_html}</div>' if tags else ''}
      </div>
      {sections_html}
      <div class="footer">
        Generated by MVM Interactive Renderer &middot; {html.escape(title)}
      </div>
    </div>
  </main>
</div>
<script>
{self._get_js()}
</script>
</body>
</html>"""

    def _render_sections(self, sections: list) -> str:
        parts = []
        for s in sections:
            if not isinstance(s, DataObject):
                continue
            fmt = s.get("format", "paragraph")
            children = s.get("children", [])
            if children and fmt in ("tab", "accordion", "timeline", "flashcard", "quiz", "reveal"):
                parts.append(self._render_container_section(s, children))
            else:
                parts.append(self._render_basic_section(s))
        return "\n".join(parts)

    def _render_container_section(self, section: DataObject, children: list) -> str:
        fmt = section.get("format", "paragraph")
        heading = section.get("heading", "")
        group_id = heading or "default"
        if fmt == "tab":
            return self._render_tab_group(children, group_id, heading)
        elif fmt == "accordion":
            return self._render_accordion_group(children, group_id, heading)
        elif fmt == "timeline":
            return self._render_timeline_group(children, heading)
        elif fmt == "flashcard":
            return self._render_flashcard_group(children, heading)
        elif fmt == "quiz":
            return self._render_quiz_group(children, heading)
        elif fmt == "reveal":
            return self._render_reveal_group(children, group_id, heading)
        return self._render_basic_section(section)

    def _render_basic_section(self, section: DataObject) -> str:
        heading = section.get("heading", "")
        body = section.get("body", "")
        fmt = section.get("format", "paragraph")
        items = section.get("items", [])
        source = section.get("source", "")
        image = section.get("image", "")
        audio = section.get("audio", "")
        video = section.get("video", "")
        background = section.get("background", "")

        css_class = f"format-{fmt}" if fmt != "paragraph" else ""
        heading_html = f'<h2 class="section-heading" data-searchable>{html.escape(heading)}</h2>'

        body_html = ""
        if body:
            body_html = f'<div class="body" data-searchable>{html.escape(body)}</div>'

        items_html = ""
        if items:
            li_items = "".join(
                f'<li data-searchable>{html.escape(item)}</li>' for item in items
            )
            items_html = f'<ul class="items">{li_items}</ul>'

        source_html = ""
        if source:
            source_html = (
                f'<div class="source"><a href="{html.escape(source)}">'
                f"{html.escape(source)}</a></div>"
            )

        media_html = self._render_media(image, audio, video)

        bg_style = f' style="background-image:url({html.escape(background)});background-size:cover;background-position:center;"' if background else ""

        return (
            f'<div class="section {css_class}" data-section{bg_style}>\n'
            f"{heading_html}\n{media_html}\n{body_html}\n{items_html}\n{source_html}\n</div>"
        )

    def _render_tab_group(self, items: list, group_id: str, heading: str = "") -> str:
        safe_id = html.escape(group_id)
        heading_html = f'<h2 class="section-heading" data-searchable>{html.escape(heading)}</h2>\n' if heading else ""
        tab_btns = ""
        tab_panels = ""
        for i, s in enumerate(items):
            heading = s.get("heading", f"Tab {i+1}")
            body = s.get("body", "")
            items_list = s.get("items", [])
            active = ' active' if i == 0 else ""
            tab_btns += (
                f'<button class="tab-btn{active}" '
                f'onclick="switchTab(this, \'{safe_id}\', {i})">'
                f"{html.escape(heading)}</button>\n"
            )
            content = html.escape(body) if body else ""
            if items_list:
                content += '<ul class="items">' + "".join(
                    f"<li>{html.escape(it)}</li>" for it in items_list
                ) + "</ul>"
            tab_panels += (
                f'<div class="tab-panel{active}" '
                f'data-tab-group="{safe_id}" data-tab-index="{i}">'
                f'<div class="body">{content}</div></div>\n'
            )
        return (
            f'<div class="section tab-group" data-section>\n'
            f'{heading_html}'
            f'<div class="tab-bar">{tab_btns}</div>\n'
            f'<div class="tab-content">{tab_panels}</div>\n'
            f"</div>"
        )

    def _render_accordion_group(self, items: list, group_id: str, heading: str = "") -> str:
        safe_id = html.escape(group_id)
        heading_html = f'<h2 class="section-heading" data-searchable>{html.escape(heading)}</h2>\n' if heading else ""
        panels = ""
        for i, s in enumerate(items):
            heading = s.get("heading", f"Section {i+1}")
            body = s.get("body", "")
            items_list = s.get("items", [])
            content = html.escape(body) if body else ""
            if items_list:
                content += '<ul class="items">' + "".join(
                    f"<li>{html.escape(it)}</li>" for it in items_list
                ) + "</ul>"
            panels += (
                f'<div class="accordion-item">\n'
                f'<button class="accordion-header" '
                f'onclick="toggleAccordion(this)">\n'
                f'<span>{html.escape(heading)}</span>\n'
                f'<span class="accordion-arrow">&#9660;</span>\n'
                f'</button>\n'
                f'<div class="accordion-body"><div class="body">{content}</div></div>\n'
                f'</div>\n'
            )
        return (
            f'<div class="section accordion-group" data-section>\n{heading_html}{panels}</div>'
        )

    def _render_timeline_group(self, items: list, heading: str = "") -> str:
        heading_html = f'<h2 class="section-heading" data-searchable>{html.escape(heading)}</h2>\n' if heading else ""
        entries = ""
        for i, s in enumerate(items):
            heading = s.get("heading", "")
            body = s.get("body", "")
            side = "left" if i % 2 == 0 else "right"
            entries += (
                f'<div class="timeline-item timeline-{side}">\n'
                f'<div class="timeline-dot"></div>\n'
                f'<div class="timeline-card">\n'
                f'<h3>{html.escape(heading)}</h3>\n'
                f'<div class="body">{html.escape(body)}</div>\n'
                f'</div>\n</div>\n'
            )
        return (
            f'<div class="section timeline-group" data-section>\n'
            f'{heading_html}<div class="timeline">{entries}</div>\n</div>'
        )

    def _render_flashcard_group(self, items: list, heading: str = "") -> str:
        heading_html = f'<h2 class="section-heading" data-searchable>{html.escape(heading)}</h2>\n' if heading else ""
        cards = ""
        for s in items:
            front = s.get("heading", "")
            back = s.get("body", "")
            cards += (
                f'<div class="flashcard" onclick="flipCard(this)">\n'
                f'<div class="flashcard-inner">\n'
                f'<div class="flashcard-front">\n'
                f'<div class="body">{html.escape(front)}</div>\n'
                f'</div>\n'
                f'<div class="flashcard-back">\n'
                f'<div class="body">{html.escape(back)}</div>\n'
                f'</div>\n'
                f'</div>\n</div>\n'
            )
        return (
            f'<div class="section flashcard-group" data-section>\n'
            f'{heading_html}<div class="flashcard-grid">{cards}</div>\n'
            f'<p class="flashcard-hint">Click card to flip</p>\n'
            f"</div>"
        )

    def _render_media(self, image: str, audio: str, video: str) -> str:
        parts = []
        if image:
            parts.append(f'<div class="media-image"><img src="{html.escape(image)}" alt="" loading="lazy"></div>')
        if video:
            parts.append(f'<div class="media-video"><video controls><source src="{html.escape(video)}">Your browser does not support video.</video></div>')
        if audio:
            parts.append(f'<div class="media-audio"><audio controls><source src="{html.escape(audio)}">Your browser does not support audio.</audio></div>')
        return "\n".join(parts)

    def _render_quiz_group(self, items: list, heading: str = "") -> str:
        heading_html = f'<h2 class="section-heading" data-searchable>{html.escape(heading)}</h2>\n' if heading else ""
        quizzes = ""
        for qi, s in enumerate(items):
            question = s.get("heading", "")
            options = s.get("items", [])
            correct = s.get("correct_answer", 0)
            explanation = s.get("body", "")
            opts_html = ""
            for oi, opt in enumerate(options):
                opts_html += (
                    f'<button class="quiz-option" '
                    f'data-quiz="{qi}" data-index="{oi}" '
                    f'data-correct="{correct}" '
                    f'onclick="checkAnswer(this)">'
                    f'<span class="quiz-label">'
                    f'{"ABCD"[oi]}</span> {html.escape(opt)}</button>\n'
                )
            quizzes += (
                f'<div class="quiz-item" data-quiz-id="{qi}">\n'
                f'<div class="quiz-question">\n'
                f'<span class="quiz-num">Q{qi+1}</span>\n'
                f'<span>{html.escape(question)}</span>\n'
                f'</div>\n'
                f'<div class="quiz-options">{opts_html}</div>\n'
                f'<div class="quiz-feedback" id="feedback-{qi}"></div>\n'
                f'<div class="quiz-explanation" id="explain-{qi}" style="display:none">'
                f'<div class="body">{html.escape(explanation)}</div></div>\n'
                f'</div>\n'
            )
        return (
            f'<div class="section quiz-group" data-section>\n{heading_html}{quizzes}</div>'
        )

    def _render_reveal_group(self, items: list, group_id: str, heading: str = "") -> str:
        safe_id = html.escape(group_id)
        heading_html = f'<h2 class="section-heading" data-searchable>{html.escape(heading)}</h2>\n' if heading else ""
        steps = ""
        for i, s in enumerate(items):
            heading = s.get("heading", "")
            body = s.get("body", "")
            steps += (
                f'<div class="reveal-step" '
                f'data-reveal-group="{safe_id}" data-reveal-step="{i}">\n'
                f'<h3>{html.escape(heading)}</h3>\n'
                f'<div class="body">{html.escape(body)}</div>\n'
                f'</div>\n'
            )
        return (
            f'<div class="section reveal-group" data-section>\n'
            f'{heading_html}<div class="reveal-steps">{steps}</div>\n'
            f'<div class="reveal-controls">\n'
            f'<button class="reveal-btn" onclick="revealNext(\'{safe_id}\', 1)">'
            f'Next &#8594;</button>\n'
            f'<button class="reveal-btn" onclick="revealNext(\'{safe_id}\', -1)">'
            f'&#8592; Prev</button>\n'
            f'<button class="reveal-btn" onclick="revealAll(\'{safe_id}\')">'
            f'Show All</button>\n'
            f'</div>\n</div>'
        )

    def _build_toc(self, sections: list) -> str:
        items = []
        idx = 0
        for s in sections:
            if not isinstance(s, DataObject):
                continue
            heading = s.get("heading", "")
            fmt = s.get("format", "paragraph")
            if not heading:
                continue
            cls = f"toc-{fmt}" if fmt != "paragraph" else ""
            items.append(
                f'<a class="toc-item {cls}" href="#section-{idx}" '
                f'data-toc="{idx}">{html.escape(heading)}</a>'
            )
            idx += 1
        return "\n".join(items)

    def _get_css(self, dark: bool) -> str:
        return """
* { margin: 0; padding: 0; box-sizing: border-box; }
:root {
  --bg: #fafafa; --bg-card: #fff; --bg-code: #1e1e2e;
  --text: #1a1a2e; --text-muted: #666; --text-light: #888;
  --accent: #3498db; --accent-light: #e8f4f8;
  --border: #e8e8e8; --shadow: rgba(0,0,0,0.06);
  --success: #27ae60; --warning: #f39c12; --danger: #e74c3c;
  --sidebar-bg: #16213e; --sidebar-text: #ccc; --sidebar-active: #3498db;
}
body.dark {
  --bg: #0d1117; --bg-card: #161b22; --bg-code: #1e1e2e;
  --text: #e6edf3; --text-muted: #8b949e; --text-light: #6e7681;
  --accent: #58a6ff; --accent-light: #1c2d41;
  --border: #30363d; --shadow: rgba(0,0,0,0.3);
  --sidebar-bg: #010409; --sidebar-text: #8b949e; --sidebar-active: #58a6ff;
}
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  line-height: 1.8; color: var(--text); background: var(--bg);
  transition: background 0.3s, color 0.3s;
}
.layout { display: flex; min-height: 100vh; }
.sidebar {
  width: 260px; background: var(--sidebar-bg); color: var(--sidebar-text);
  position: fixed; top: 0; left: 0; height: 100vh; overflow-y: auto;
  display: flex; flex-direction: column; z-index: 100;
  transition: transform 0.3s;
}
.sidebar-header {
  padding: 20px; display: flex; justify-content: space-between; align-items: center;
  border-bottom: 1px solid rgba(255,255,255,0.1);
}
.logo { font-weight: 700; font-size: 1.2em; color: #fff; }
.sidebar-close { display: none; background: none; border: none; color: #fff; font-size: 1.5em; cursor: pointer; }
.toc { flex: 1; padding: 12px 0; }
.toc-item {
  display: block; padding: 8px 20px; color: var(--sidebar-text);
  text-decoration: none; font-size: 0.85em; border-left: 3px solid transparent;
  transition: all 0.2s;
}
.toc-item:hover, .toc-item.active {
  color: #fff; border-left-color: var(--sidebar-active);
  background: rgba(255,255,255,0.05);
}
.sidebar-footer {
  padding: 12px 20px; border-top: 1px solid rgba(255,255,255,0.1);
  display: flex; gap: 8px;
}
.sidebar-footer button {
  background: rgba(255,255,255,0.1); border: none; color: #fff;
  padding: 6px 10px; border-radius: 6px; cursor: pointer; font-size: 1em;
}
.sidebar-footer button:hover { background: rgba(255,255,255,0.2); }
.content { flex: 1; margin-left: 260px; }
.toolbar {
  position: sticky; top: 0; z-index: 50; background: var(--bg);
  border-bottom: 1px solid var(--border); padding: 10px 24px;
  display: flex; align-items: center; gap: 12px;
  transition: background 0.3s;
}
.menu-btn { display: none; background: none; border: none; font-size: 1.4em; cursor: pointer; color: var(--text); }
.search-box { flex: 1; max-width: 400px; }
.search-box input {
  width: 100%; padding: 6px 14px; border: 1px solid var(--border);
  border-radius: 20px; background: var(--bg-card); color: var(--text);
  font-size: 0.9em; outline: none; transition: border 0.2s;
}
.search-box input:focus { border-color: var(--accent); }
.progress-bar {
  flex: 1; height: 3px; background: var(--border); border-radius: 2px; overflow: hidden;
}
.progress-fill {
  height: 100%; width: 0%; background: var(--accent);
  transition: width 0.1s; border-radius: 2px;
}
.container { max-width: 800px; margin: 0 auto; padding: 40px 24px; }
.header { margin-bottom: 48px; padding-bottom: 32px; border-bottom: 2px solid var(--border); }
.header h1 { font-size: 2.2em; font-weight: 700; margin-bottom: 8px; color: var(--text); }
.header .subtitle { font-size: 1.2em; color: var(--text-muted); margin-bottom: 16px; }
.meta { display: flex; gap: 16px; flex-wrap: wrap; color: var(--text-light); font-size: 0.9em; margin-bottom: 12px; }
.tags { display: flex; gap: 8px; flex-wrap: wrap; }
.tag { background: var(--accent-light); color: var(--accent); padding: 2px 12px; border-radius: 12px; font-size: 0.85em; }
.section { margin-bottom: 36px; }
.section h2.section-heading {
  font-size: 1.5em; font-weight: 600; margin-bottom: 12px;
  padding-left: 12px; border-left: 4px solid var(--accent);
}
.section.format-quote {
  background: var(--accent-light); border-left: 4px solid var(--accent);
  padding: 20px 24px; border-radius: 0 8px 8px 0; margin: 24px 0;
}
.section.format-quote h2.section-heading {
  border-left: none; padding-left: 0; color: var(--accent); font-size: 1.1em;
}
.section.format-code {
  background: var(--bg-code); color: #cdd6f4;
  padding: 20px 24px; border-radius: 8px; margin: 24px 0;
  font-family: 'Fira Code', 'Consolas', monospace; font-size: 0.9em;
}
.section.format-code h2.section-heading {
  color: #89b4fa; border-left-color: #89b4fa; background: none;
  padding: 0 0 12px 12px; font-size: 1.1em;
}
.section.format-tip {
  background: #fef9e7; border-left: 4px solid var(--warning);
  padding: 20px 24px; border-radius: 0 8px 8px 0; margin: 24px 0;
}
body.dark .section.format-tip { background: #2d2006; }
.section.format-tip h2.section-heading {
  border-left: none; padding-left: 0; color: var(--warning); font-size: 1.1em;
}
.section.format-warning {
  background: #fdedec; border-left: 4px solid var(--danger);
  padding: 20px 24px; border-radius: 0 8px 8px 0; margin: 24px 0;
}
body.dark .section.format-warning { background: #2d1215; }
.section.format-warning h2.section-heading {
  border-left: none; padding-left: 0; color: var(--danger); font-size: 1.1em;
}
.section.format-list h2.section-heading { border-left-color: var(--success); }
.body { margin-top: 8px; white-space: pre-wrap; }
.items { list-style: none; padding: 0; margin-top: 12px; }
.items li { padding: 6px 0 6px 20px; position: relative; }
.items li::before { content: "\\2022"; position: absolute; left: 0; color: var(--accent); font-weight: bold; }
.source { margin-top: 8px; font-size: 0.85em; }
.source a { color: var(--accent); text-decoration: none; }
.source a:hover { text-decoration: underline; }
.media-image { margin: 12px 0; }
.media-image img { max-width: 100%; height: auto; border-radius: 8px; }
.media-video { margin: 12px 0; }
.media-video video { max-width: 100%; border-radius: 8px; }
.media-audio { margin: 12px 0; }
.media-audio audio { width: 100%; }
.section { background-size: cover; background-position: center; }
.footer {
  margin-top: 48px; padding-top: 24px; border-top: 1px solid var(--border);
  color: var(--text-light); font-size: 0.85em; text-align: center;
}

/* Tab */
.tab-bar {
  display: flex; gap: 0; border-bottom: 2px solid var(--border); margin-bottom: 16px;
}
.tab-btn {
  padding: 10px 20px; background: none; border: none; border-bottom: 3px solid transparent;
  color: var(--text-muted); cursor: pointer; font-size: 0.95em; font-weight: 500;
  transition: all 0.2s; margin-bottom: -2px;
}
.tab-btn:hover { color: var(--text); }
.tab-btn.active { color: var(--accent); border-bottom-color: var(--accent); }
.tab-panel { display: none; padding: 16px 0; animation: fadeIn 0.3s; }
.tab-panel.active { display: block; }

/* Accordion */
.accordion-item { border: 1px solid var(--border); border-radius: 8px; margin-bottom: 8px; overflow: hidden; }
.accordion-header {
  width: 100%; padding: 14px 18px; background: var(--bg-card); border: none;
  display: flex; justify-content: space-between; align-items: center;
  cursor: pointer; font-size: 1em; color: var(--text); text-align: left;
  transition: background 0.2s;
}
.accordion-header:hover { background: var(--accent-light); }
.accordion-arrow { transition: transform 0.3s; font-size: 0.8em; }
.accordion-item.open .accordion-arrow { transform: rotate(180deg); }
.accordion-body { max-height: 0; overflow: hidden; transition: max-height 0.4s ease; }
.accordion-item.open .accordion-body { max-height: 2000px; }
.accordion-body .body { padding: 0 18px 14px; }

/* Timeline */
.timeline { position: relative; padding: 20px 0; }
.timeline::before {
  content: ''; position: absolute; left: 50%; top: 0; bottom: 0;
  width: 3px; background: var(--border); transform: translateX(-50%);
}
.timeline-item { display: flex; margin-bottom: 32px; position: relative; }
.timeline-left { justify-content: flex-start; padding-right: calc(50% + 30px); text-align: right; }
.timeline-right { justify-content: flex-end; padding-left: calc(50% + 30px); }
.timeline-dot {
  position: absolute; left: 50%; top: 16px; width: 14px; height: 14px;
  background: var(--accent); border-radius: 50%; transform: translateX(-50%);
  border: 3px solid var(--bg); z-index: 1;
}
.timeline-card {
  background: var(--bg-card); border: 1px solid var(--border);
  padding: 16px 20px; border-radius: 8px; box-shadow: 0 2px 8px var(--shadow);
}
.timeline-card h3 { font-size: 1.1em; margin-bottom: 6px; color: var(--accent); }

/* Flashcard */
.flashcard-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 20px; }
.flashcard {
  height: 200px; perspective: 600px; cursor: pointer;
}
.flashcard-inner {
  width: 100%; height: 100%; position: relative;
  transition: transform 0.6s; transform-style: preserve-3d;
}
.flashcard.flipped .flashcard-inner { transform: rotateY(180deg); }
.flashcard-front, .flashcard-back {
  position: absolute; width: 100%; height: 100%; backface-visibility: hidden;
  display: flex; align-items: center; justify-content: center; padding: 20px;
  border-radius: 12px; text-align: center;
}
.flashcard-front { background: var(--accent); color: #fff; font-weight: 600; }
.flashcard-back { background: var(--bg-card); border: 2px solid var(--accent); transform: rotateY(180deg); }
.flashcard-hint { text-align: center; color: var(--text-light); font-size: 0.85em; margin-top: 12px; }

/* Quiz */
.quiz-item {
  background: var(--bg-card); border: 1px solid var(--border);
  border-radius: 12px; padding: 24px; margin-bottom: 20px;
  box-shadow: 0 2px 8px var(--shadow);
}
.quiz-question { display: flex; gap: 10px; margin-bottom: 16px; font-size: 1.1em; font-weight: 600; }
.quiz-num {
  background: var(--accent); color: #fff; padding: 2px 10px;
  border-radius: 6px; font-size: 0.85em; flex-shrink: 0;
}
.quiz-options { display: flex; flex-direction: column; gap: 8px; }
.quiz-option {
  padding: 12px 16px; border: 2px solid var(--border); border-radius: 8px;
  background: var(--bg); cursor: pointer; text-align: left;
  font-size: 0.95em; color: var(--text); transition: all 0.2s;
  display: flex; align-items: center; gap: 10px;
}
.quiz-option:hover:not(.disabled) { border-color: var(--accent); background: var(--accent-light); }
.quiz-option.correct { border-color: var(--success); background: #e8f8f0; }
.quiz-option.wrong { border-color: var(--danger); background: #fdecea; }
.quiz-option.disabled { cursor: default; opacity: 0.7; }
.quiz-label {
  background: var(--border); color: var(--text-muted); padding: 2px 8px;
  border-radius: 4px; font-size: 0.8em; font-weight: 700; flex-shrink: 0;
}
.quiz-feedback { margin-top: 12px; font-weight: 600; font-size: 0.95em; }
.quiz-explanation { margin-top: 12px; padding: 12px; background: var(--accent-light); border-radius: 8px; }

/* Reveal */
.reveal-step {
  opacity: 0; transform: translateY(20px);
  transition: opacity 0.5s, transform 0.5s; margin-bottom: 16px;
  padding: 16px; border-left: 3px solid var(--accent);
}
.reveal-step.visible { opacity: 1; transform: translateY(0); }
.reveal-controls { display: flex; gap: 8px; margin-top: 16px; }
.reveal-btn {
  padding: 8px 16px; border: 1px solid var(--border); border-radius: 6px;
  background: var(--bg-card); color: var(--text); cursor: pointer; font-size: 0.9em;
}
.reveal-btn:hover { background: var(--accent-light); border-color: var(--accent); }

/* Search highlight */
.search-hidden { display: none !important; }
mark { background: #fff3cd; padding: 0 2px; border-radius: 2px; }
body.dark mark { background: #3d3400; }

/* Animations */
@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }

/* Responsive */
@media (max-width: 768px) {
  .sidebar { transform: translateX(-100%); }
  .sidebar.open { transform: translateX(0); }
  .sidebar-close { display: block; }
  .content { margin-left: 0; }
  .menu-btn { display: block; }
  .timeline::before { left: 20px; }
  .timeline-item { padding-left: 50px !important; padding-right: 0 !important; text-align: left !important; }
  .timeline-dot { left: 20px; }
  .flashcard-grid { grid-template-columns: 1fr; }
}
"""  # noqa: E501

    def _get_js(self) -> str:
        return """
function switchTab(btn, groupId, index) {
  var bar = btn.parentElement;
  var btns = bar.querySelectorAll('.tab-btn');
  btns.forEach(function(b) { b.classList.remove('active'); });
  btn.classList.add('active');
  var panels = document.querySelectorAll('[data-tab-group="' + groupId + '"]');
  panels.forEach(function(p) {
    p.classList.toggle('active', parseInt(p.dataset.tabIndex) === index);
  });
}

function toggleAccordion(header) {
  var item = header.parentElement;
  var wasOpen = item.classList.contains('open');
  var group = item.parentElement;
  group.querySelectorAll('.accordion-item').forEach(function(ai) {
    ai.classList.remove('open');
  });
  if (!wasOpen) item.classList.add('open');
}

function flipCard(card) {
  card.classList.toggle('flipped');
}

function checkAnswer(btn) {
  var quizId = btn.dataset.quiz;
  var idx = parseInt(btn.dataset.index);
  var correct = parseInt(btn.dataset.correct);
  var options = document.querySelectorAll('[data-quiz="' + quizId + '"]');
  var feedback = document.getElementById('feedback-' + quizId);
  var explain = document.getElementById('explain-' + quizId);
  options.forEach(function(o) { o.classList.add('disabled'); });
  if (idx === correct) {
    btn.classList.add('correct');
    feedback.textContent = 'Correct!';
    feedback.style.color = 'var(--success)';
  } else {
    btn.classList.add('wrong');
    options[correct].classList.add('correct');
    feedback.textContent = 'Incorrect. The correct answer is highlighted.';
    feedback.style.color = 'var(--danger)';
  }
  if (explain.textContent.trim()) explain.style.display = 'block';
}

var revealCounters = {};
function revealNext(groupId, dir) {
  if (!revealCounters[groupId]) revealCounters[groupId] = 0;
  var steps = document.querySelectorAll('[data-reveal-group="' + groupId + '"]');
  var total = steps.length;
  revealCounters[groupId] = Math.max(0, Math.min(total, revealCounters[groupId] + dir));
  steps.forEach(function(s, i) {
    s.classList.toggle('visible', i < revealCounters[groupId]);
  });
}
function revealAll(groupId) {
  var steps = document.querySelectorAll('[data-reveal-group="' + groupId + '"]');
  steps.forEach(function(s) { s.classList.add('visible'); });
  revealCounters[groupId] = steps.length;
}

function filterSections(query) {
  var sections = document.querySelectorAll('[data-section]');
  query = query.toLowerCase().trim();
  sections.forEach(function(s) {
    if (!query) {
      s.classList.remove('search-hidden');
      s.querySelectorAll('mark').forEach(function(m) {
        var parent = m.parentNode;
        parent.replaceChild(document.createTextNode(m.textContent), m);
        parent.normalize();
      });
      return;
    }
    var text = s.textContent.toLowerCase();
    if (text.indexOf(query) >= 0) {
      s.classList.remove('search-hidden');
    } else {
      s.classList.add('search-hidden');
    }
  });
}

function toggleTheme() {
  document.body.classList.toggle('dark');
  var icon = document.getElementById('themeIcon');
  icon.innerHTML = document.body.classList.contains('dark') ? '&#9728;' : '&#9790;';
}

function toggleFullscreen() {
  if (!document.fullscreenElement) {
    document.documentElement.requestFullscreen();
  } else {
    document.exitFullscreen();
  }
}

window.addEventListener('scroll', function() {
  var fill = document.getElementById('progressFill');
  var scrollTop = document.documentElement.scrollTop || document.body.scrollTop;
  var scrollHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight;
  fill.style.width = (scrollTop / scrollHeight * 100) + '%';

  var items = document.querySelectorAll('.toc-item');
  var sections = document.querySelectorAll('[data-section]');
  var current = -1;
  sections.forEach(function(s, i) {
    if (s.getBoundingClientRect().top < 150) current = i;
  });
  items.forEach(function(item, i) {
    item.classList.toggle('active', i === current);
  });
});

document.addEventListener('keydown', function(e) {
  if (e.key === '/' && !e.ctrlKey && !e.metaKey) {
    var input = document.getElementById('searchInput');
    if (document.activeElement !== input) {
      e.preventDefault();
      input.focus();
    }
  }
  if (e.key === 'Escape') {
    document.getElementById('searchInput').blur();
    document.getElementById('searchInput').value = '';
    filterSections('');
  }
});
"""
