"""
InteractiveWebRenderer - 交互式网页渲染器
将 MVM 解析结果渲染为带交互能力的完整 HTML 页面
所有交互逻辑由渲染器注入，.mvm 文件本身不包含任何 JavaScript
"""

import html
from ..data_object import DataObject
from ..renderers import BaseRenderer
from ..plugins.loader import PluginLoader


class InteractiveWebRenderer(BaseRenderer):
    capabilities = ["interactive", "media", "tree", "dark_mode", "search", "toc"]
    def __init__(self):
        self._plugin_loader = PluginLoader()
        self._plugin_loader.load_builtin_plugins()

    def load_plugins_from_dir(self, directory: str) -> int:
        return self._plugin_loader.load_from_directory(directory)

    def file_extension(self) -> str:
        return "html"

    def render(self, result, dark: bool = False) -> str:
        data = result.data
        title = data.get("title", "MVM Document")
        subtitle = data.get("subtitle", "")
        author = data.get("author", "")
        date = data.get("date", "")
        tags = data.get("tags", [])
        sections = data.get("sections", [])

        sections_html = self._render_sections(sections)

        tags_html = " ".join(
            f'<span class="tag">{html.escape(t)}</span>' for t in tags
        )

        toc_html = self._build_toc(sections)

        dark_class = "dark" if dark else ""

        return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(title)}</title>
<style>
{self._get_css(dark)}
{self._get_plugin_css()}
</style>
</head>
<body class="{dark_class}">
<div class="layout">
  <aside class="sidebar" id="sidebar">
    <div class="sidebar-header">
      <span class="logo">MVM</span>
      <button class="sidebar-close" onclick="document.getElementById('sidebar').classList.remove('open')" aria-label="Close">&times;</button>
    </div>
    <nav class="toc" id="toc">
      {toc_html}
    </nav>
    <div class="sidebar-footer">
      <button class="theme-toggle" onclick="toggleTheme()" title="Toggle theme">
        <span class="theme-icon" id="themeIcon">&#9790;</span>
      </button>
      <button class="fullscreen-btn" onclick="toggleFullscreen()" title="Fullscreen">&#x26F6;</button>
    </div>
  </aside>
  <main class="content" id="content">
    <div class="toolbar">
      <button class="menu-btn" onclick="document.getElementById('sidebar').classList.add('open')" aria-label="Menu">&#9776;</button>
      <div class="search-box">
        <input type="text" id="searchInput" placeholder="Search sections..." oninput="filterSections(this.value)">
      </div>
      <div class="progress-bar"><div class="progress-fill" id="progressFill"></div></div>
    </div>
    <div class="container">
      <div class="header">
        <h1>{html.escape(title)}</h1>
        {f'<div class="subtitle">{html.escape(subtitle)}</div>' if subtitle else ''}
        <div class="meta">
          {f'<span>{html.escape(author)}</span>' if author else ''}
          {f'<span>{html.escape(date)}</span>' if date else ''}
        </div>
        {f'<div class="tags">{tags_html}</div>' if tags else ''}
      </div>
      {sections_html}
      <div class="footer">
        Generated by MVM Interactive Renderer &middot; {html.escape(title)}
      </div>
    </div>
  </main>
</div>
<script>
{self._get_js()}
{self._get_plugin_js()}
</script>
</body>
</html>"""

    def _render_sections(self, sections: list) -> str:
        parts = []
        for s in sections:
            if not isinstance(s, DataObject):
                continue
            fmt = s.get("format", "paragraph")
            children = s.get("children", [])
            if children and self._plugin_loader.has(fmt):
                parts.append(self._render_container_section(s, children))
            else:
                parts.append(self._render_basic_section(s))
        return "\n".join(parts)

    def _render_container_section(self, section: DataObject, children: list) -> str:
        fmt = section.get("format", "paragraph")
        plugin = self._plugin_loader.get(fmt)
        if plugin:
            return plugin.render(section, children)
        return self._render_basic_section(section)

    def _render_basic_section(self, section: DataObject) -> str:
        heading = section.get("heading", "")
        body = section.get("body", "")
        fmt = section.get("format", "paragraph")
        items = section.get("items", [])
        source = section.get("source", "")
        image = section.get("image", "")
        audio = section.get("audio", "")
        video = section.get("video", "")
        background = section.get("background", "")

        css_class = f"format-{fmt}" if fmt != "paragraph" else ""
        heading_html = f'<h2 class="section-heading" data-searchable>{html.escape(heading)}</h2>'

        body_html = ""
        if body:
            body_html = f'<div class="body" data-searchable>{html.escape(body)}</div>'

        items_html = ""
        if items:
            li_items = "".join(
                f'<li data-searchable>{html.escape(item)}</li>' for item in items
            )
            items_html = f'<ul class="items">{li_items}</ul>'

        source_html = ""
        if source:
            source_html = (
                f'<div class="source"><a href="{html.escape(source)}">'
                f"{html.escape(source)}</a></div>"
            )

        media_html = self._render_media(image, audio, video)

        bg_style = f' style="background-image:url({html.escape(background)});background-size:cover;background-position:center;"' if background else ""

        return (
            f'<div class="section {css_class}" data-section{bg_style}>\n'
            f"{heading_html}\n{media_html}\n{body_html}\n{items_html}\n{source_html}\n</div>"
        )

    def _render_media(self, image: str, audio: str, video: str) -> str:
        parts = []
        if image:
            parts.append(f'<div class="media-image"><img src="{html.escape(image)}" alt="" loading="lazy"></div>')
        if video:
            parts.append(f'<div class="media-video"><video controls><source src="{html.escape(video)}">Your browser does not support video.</video></div>')
        if audio:
            parts.append(f'<div class="media-audio"><audio controls><source src="{html.escape(audio)}">Your browser does not support audio.</audio></div>')
        return "\n".join(parts)

    def _build_toc(self, sections: list) -> str:
        items = []
        idx = 0
        for s in sections:
            if not isinstance(s, DataObject):
                continue
            heading = s.get("heading", "")
            fmt = s.get("format", "paragraph")
            if not heading:
                continue
            cls = f"toc-{fmt}" if fmt != "paragraph" else ""
            items.append(
                f'<a class="toc-item {cls}" href="#section-{idx}" '
                f'data-toc="{idx}">{html.escape(heading)}</a>'
            )
            idx += 1
        return "\n".join(items)

    def _get_plugin_css(self) -> str:
        parts = []
        for name in self._plugin_loader.list_names():
            plugin = self._plugin_loader.get(name)
            if plugin:
                css = plugin.get_css()
                if css.strip():
                    parts.append(f"/* Plugin: {name} */\n{css}")
        return "\n".join(parts)

    def _get_plugin_js(self) -> str:
        parts = []
        for name in self._plugin_loader.list_names():
            plugin = self._plugin_loader.get(name)
            if plugin:
                js = plugin.get_js()
                if js.strip():
                    parts.append(f"// Plugin: {name}\n{js}")
        return "\n".join(parts)

    def _get_css(self, dark: bool) -> str:
        return """
* { margin: 0; padding: 0; box-sizing: border-box; }
:root {
  --bg: #fafafa; --bg-card: #fff; --bg-code: #1e1e2e;
  --text: #1a1a2e; --text-muted: #666; --text-light: #888;
  --accent: #3498db; --accent-light: #e8f4f8;
  --border: #e8e8e8; --shadow: rgba(0,0,0,0.06);
  --success: #27ae60; --warning: #f39c12; --danger: #e74c3c;
  --sidebar-bg: #16213e; --sidebar-text: #ccc; --sidebar-active: #3498db;
}
body.dark {
  --bg: #0d1117; --bg-card: #161b22; --bg-code: #1e1e2e;
  --text: #e6edf3; --text-muted: #8b949e; --text-light: #6e7681;
  --accent: #58a6ff; --accent-light: #1c2d41;
  --border: #30363d; --shadow: rgba(0,0,0,0.3);
  --sidebar-bg: #010409; --sidebar-text: #8b949e; --sidebar-active: #58a6ff;
}
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  line-height: 1.8; color: var(--text); background: var(--bg);
  transition: background 0.3s, color 0.3s;
}
.layout { display: flex; min-height: 100vh; }
.sidebar {
  width: 260px; background: var(--sidebar-bg); color: var(--sidebar-text);
  position: fixed; top: 0; left: 0; height: 100vh; overflow-y: auto;
  display: flex; flex-direction: column; z-index: 100;
  transition: transform 0.3s;
}
.sidebar-header {
  padding: 20px; display: flex; justify-content: space-between; align-items: center;
  border-bottom: 1px solid rgba(255,255,255,0.1);
}
.logo { font-weight: 700; font-size: 1.2em; color: #fff; }
.sidebar-close { display: none; background: none; border: none; color: #fff; font-size: 1.5em; cursor: pointer; }
.toc { flex: 1; padding: 12px 0; }
.toc-item {
  display: block; padding: 8px 20px; color: var(--sidebar-text);
  text-decoration: none; font-size: 0.85em; border-left: 3px solid transparent;
  transition: all 0.2s;
}
.toc-item:hover, .toc-item.active {
  color: #fff; border-left-color: var(--sidebar-active);
  background: rgba(255,255,255,0.05);
}
.sidebar-footer {
  padding: 12px 20px; border-top: 1px solid rgba(255,255,255,0.1);
  display: flex; gap: 8px;
}
.sidebar-footer button {
  background: rgba(255,255,255,0.1); border: none; color: #fff;
  padding: 6px 10px; border-radius: 6px; cursor: pointer; font-size: 1em;
}
.sidebar-footer button:hover { background: rgba(255,255,255,0.2); }
.content { flex: 1; margin-left: 260px; }
.toolbar {
  position: sticky; top: 0; z-index: 50; background: var(--bg);
  border-bottom: 1px solid var(--border); padding: 10px 24px;
  display: flex; align-items: center; gap: 12px;
  transition: background 0.3s;
}
.menu-btn { display: none; background: none; border: none; font-size: 1.4em; cursor: pointer; color: var(--text); }
.search-box { flex: 1; max-width: 400px; }
.search-box input {
  width: 100%; padding: 6px 14px; border: 1px solid var(--border);
  border-radius: 20px; background: var(--bg-card); color: var(--text);
  font-size: 0.9em; outline: none; transition: border 0.2s;
}
.search-box input:focus { border-color: var(--accent); }
.progress-bar {
  flex: 1; height: 3px; background: var(--border); border-radius: 2px; overflow: hidden;
}
.progress-fill {
  height: 100%; width: 0%; background: var(--accent);
  transition: width 0.1s; border-radius: 2px;
}
.container { max-width: 800px; margin: 0 auto; padding: 40px 24px; }
.header { margin-bottom: 48px; padding-bottom: 32px; border-bottom: 2px solid var(--border); }
.header h1 { font-size: 2.2em; font-weight: 700; margin-bottom: 8px; color: var(--text); }
.header .subtitle { font-size: 1.2em; color: var(--text-muted); margin-bottom: 16px; }
.meta { display: flex; gap: 16px; flex-wrap: wrap; color: var(--text-light); font-size: 0.9em; margin-bottom: 12px; }
.tags { display: flex; gap: 8px; flex-wrap: wrap; }
.tag { background: var(--accent-light); color: var(--accent); padding: 2px 12px; border-radius: 12px; font-size: 0.85em; }
.section { margin-bottom: 36px; }
.section h2.section-heading {
  font-size: 1.5em; font-weight: 600; margin-bottom: 12px;
  padding-left: 12px; border-left: 4px solid var(--accent);
}
.section.format-quote {
  background: var(--accent-light); border-left: 4px solid var(--accent);
  padding: 20px 24px; border-radius: 0 8px 8px 0; margin: 24px 0;
}
.section.format-quote h2.section-heading {
  border-left: none; padding-left: 0; color: var(--accent); font-size: 1.1em;
}
.section.format-code {
  background: var(--bg-code); color: #cdd6f4;
  padding: 20px 24px; border-radius: 8px; margin: 24px 0;
  font-family: 'Fira Code', 'Consolas', monospace; font-size: 0.9em;
}
.section.format-code h2.section-heading {
  color: #89b4fa; border-left-color: #89b4fa; background: none;
  padding: 0 0 12px 12px; font-size: 1.1em;
}
.section.format-tip {
  background: #fef9e7; border-left: 4px solid var(--warning);
  padding: 20px 24px; border-radius: 0 8px 8px 0; margin: 24px 0;
}
body.dark .section.format-tip { background: #2d2006; }
.section.format-tip h2.section-heading {
  border-left: none; padding-left: 0; color: var(--warning); font-size: 1.1em;
}
.section.format-warning {
  background: #fdedec; border-left: 4px solid var(--danger);
  padding: 20px 24px; border-radius: 0 8px 8px 0; margin: 24px 0;
}
body.dark .section.format-warning { background: #2d1215; }
.section.format-warning h2.section-heading {
  border-left: none; padding-left: 0; color: var(--danger); font-size: 1.1em;
}
.section.format-list h2.section-heading { border-left-color: var(--success); }
.body { margin-top: 8px; white-space: pre-wrap; }
.items { list-style: none; padding: 0; margin-top: 12px; }
.items li { padding: 6px 0 6px 20px; position: relative; }
.items li::before { content: "\\2022"; position: absolute; left: 0; color: var(--accent); font-weight: bold; }
.source { margin-top: 8px; font-size: 0.85em; }
.source a { color: var(--accent); text-decoration: none; }
.source a:hover { text-decoration: underline; }
.media-image { margin: 12px 0; }
.media-image img { max-width: 100%; height: auto; border-radius: 8px; }
.media-video { margin: 12px 0; }
.media-video video { max-width: 100%; border-radius: 8px; }
.media-audio { margin: 12px 0; }
.media-audio audio { width: 100%; }
.section { background-size: cover; background-position: center; }
.footer {
  margin-top: 48px; padding-top: 24px; border-top: 1px solid var(--border);
  color: var(--text-light); font-size: 0.85em; text-align: center;
}

/* Search highlight */
.search-hidden { display: none !important; }
mark { background: #fff3cd; padding: 0 2px; border-radius: 2px; }
body.dark mark { background: #3d3400; }

/* Animations */
@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }

/* Responsive */
@media (max-width: 768px) {
  .sidebar { transform: translateX(-100%); }
  .sidebar.open { transform: translateX(0); }
  .sidebar-close { display: block; }
  .content { margin-left: 0; }
  .menu-btn { display: block; }
}
"""  # noqa: E501

    def _get_js(self) -> str:
        return """
function filterSections(query) {
  var sections = document.querySelectorAll('[data-section]');
  query = query.toLowerCase().trim();
  sections.forEach(function(s) {
    if (!query) {
      s.classList.remove('search-hidden');
      s.querySelectorAll('mark').forEach(function(m) {
        var parent = m.parentNode;
        parent.replaceChild(document.createTextNode(m.textContent), m);
        parent.normalize();
      });
      return;
    }
    var text = s.textContent.toLowerCase();
    if (text.indexOf(query) >= 0) {
      s.classList.remove('search-hidden');
    } else {
      s.classList.add('search-hidden');
    }
  });
}

function toggleTheme() {
  document.body.classList.toggle('dark');
  var icon = document.getElementById('themeIcon');
  icon.innerHTML = document.body.classList.contains('dark') ? '&#9728;' : '&#9790;';
}

function toggleFullscreen() {
  if (!document.fullscreenElement) {
    document.documentElement.requestFullscreen();
  } else {
    document.exitFullscreen();
  }
}

window.addEventListener('scroll', function() {
  var fill = document.getElementById('progressFill');
  var scrollTop = document.documentElement.scrollTop || document.body.scrollTop;
  var scrollHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight;
  fill.style.width = (scrollTop / scrollHeight * 100) + '%';

  var items = document.querySelectorAll('.toc-item');
  var sections = document.querySelectorAll('[data-section]');
  var current = -1;
  sections.forEach(function(s, i) {
    if (s.getBoundingClientRect().top < 150) current = i;
  });
  items.forEach(function(item, i) {
    item.classList.toggle('active', i === current);
  });
});

document.addEventListener('keydown', function(e) {
  if (e.key === '/' && !e.ctrlKey && !e.metaKey) {
    var input = document.getElementById('searchInput');
    if (document.activeElement !== input) {
      e.preventDefault();
      input.focus();
    }
  }
  if (e.key === 'Escape') {
    document.getElementById('searchInput').blur();
    document.getElementById('searchInput').value = '';
    filterSections('');
  }
});
"""
