"""
WebRenderer - 网页渲染器
将 MVM 解析结果渲染为完整的 HTML 页面
"""

import html
from ..data_object import DataObject
from ..renderers import BaseRenderer


class WebRenderer(BaseRenderer):
    def file_extension(self) -> str:
        return "html"

    def render(self, result) -> str:
        data = result.data
        title = data.get("title", "MVM Document")
        subtitle = data.get("subtitle", "")
        author = data.get("author", "")
        date = data.get("date", "")
        tags = data.get("tags", [])
        sections = data.get("sections", [])

        sections_html = ""
        for section in sections:
            if isinstance(section, DataObject):
                sections_html += self._render_section(section)

        tags_html = " ".join(f'<span class="tag">{html.escape(t)}</span>' for t in tags)

        return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(title)}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  line-height: 1.8;
  color: #1a1a2e;
  background: #fafafa;
}}
.container {{
  max-width: 800px;
  margin: 0 auto;
  padding: 40px 24px;
}}
.header {{
  margin-bottom: 48px;
  padding-bottom: 32px;
  border-bottom: 2px solid #e8e8e8;
}}
.header h1 {{
  font-size: 2.2em;
  font-weight: 700;
  margin-bottom: 8px;
  color: #16213e;
}}
.header .subtitle {{
  font-size: 1.2em;
  color: #666;
  margin-bottom: 16px;
}}
.meta {{
  display: flex;
  gap: 16px;
  flex-wrap: wrap;
  color: #888;
  font-size: 0.9em;
  margin-bottom: 12px;
}}
.tags {{
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}}
.tag {{
  background: #e8f4f8;
  color: #2980b9;
  padding: 2px 12px;
  border-radius: 12px;
  font-size: 0.85em;
}}
.section {{
  margin-bottom: 36px;
}}
.section h2 {{
  font-size: 1.5em;
  font-weight: 600;
  margin-bottom: 12px;
  color: #16213e;
  padding-left: 12px;
  border-left: 4px solid #3498db;
}}
.section.format-quote {{
  background: #f0f7ff;
  border-left: 4px solid #3498db;
  padding: 20px 24px;
  border-radius: 0 8px 8px 0;
  margin: 24px 0;
}}
.section.format-quote h2 {{
  border-left: none;
  padding-left: 0;
  margin-bottom: 8px;
  font-size: 1.1em;
  color: #2980b9;
}}
.section.format-code {{
  background: #1e1e2e;
  color: #cdd6f4;
  padding: 20px 24px;
  border-radius: 8px;
  margin: 24px 0;
  font-family: 'Fira Code', 'Consolas', monospace;
  font-size: 0.9em;
  line-height: 1.6;
  white-space: pre-wrap;
  word-break: break-all;
}}
.section.format-code h2 {{
  color: #89b4fa;
  border-left-color: #89b4fa;
  background: none;
  padding: 0 0 12px 12px;
  margin-bottom: 16px;
  font-size: 1.1em;
}}
.section.format-code .body {{
  white-space: pre-wrap;
}}
.section.format-list h2 {{
  border-left-color: #27ae60;
}}
.section.format-tip {{
  background: #fef9e7;
  border-left: 4px solid #f39c12;
  padding: 20px 24px;
  border-radius: 0 8px 8px 0;
  margin: 24px 0;
}}
.section.format-tip h2 {{
  border-left: none;
  padding-left: 0;
  margin-bottom: 8px;
  font-size: 1.1em;
  color: #e67e22;
}}
.section.format-warning {{
  background: #fdedec;
  border-left: 4px solid #e74c3c;
  padding: 20px 24px;
  border-radius: 0 8px 8px 0;
  margin: 24px 0;
}}
.section.format-warning h2 {{
  border-left: none;
  padding-left: 0;
  margin-bottom: 8px;
  font-size: 1.1em;
  color: #c0392b;
}}
.body {{
  margin-top: 8px;
  white-space: pre-wrap;
}}
.items {{
  list-style: none;
  padding: 0;
  margin-top: 12px;
}}
.items li {{
  padding: 6px 0 6px 20px;
  position: relative;
}}
.items li::before {{
  content: "\\2022";
  position: absolute;
  left: 0;
  color: #3498db;
  font-weight: bold;
}}
.source {{
  margin-top: 8px;
  font-size: 0.85em;
}}
.source a {{
  color: #3498db;
  text-decoration: none;
}}
.source a:hover {{
  text-decoration: underline;
}}
.footer {{
  margin-top: 48px;
  padding-top: 24px;
  border-top: 1px solid #e8e8e8;
  color: #aaa;
  font-size: 0.85em;
  text-align: center;
}}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>{html.escape(title)}</h1>
    {f'<div class="subtitle">{html.escape(subtitle)}</div>' if subtitle else ''}
    <div class="meta">
      {f'<span>{html.escape(author)}</span>' if author else ''}
      {f'<span>{html.escape(date)}</span>' if date else ''}
    </div>
    {f'<div class="tags">{tags_html}</div>' if tags else ''}
  </div>
  {sections_html}
  <div class="footer">
    Generated by MVM Parser &middot; {html.escape(title)}
  </div>
</div>
</body>
</html>"""

    def _render_section(self, section: DataObject) -> str:
        heading = section.get("heading", "")
        body = section.get("body", "")
        fmt = section.get("format", "paragraph")
        items = section.get("items", [])
        source = section.get("source", "")

        css_class = f"format-{fmt}" if fmt != "paragraph" else ""
        heading_html = f"<h2>{html.escape(heading)}</h2>"

        body_html = ""
        if body:
            escaped_body = html.escape(body)
            body_html = f'<div class="body">{escaped_body}</div>'

        items_html = ""
        if items:
            li_items = "".join(f"<li>{html.escape(item)}</li>" for item in items)
            items_html = f'<ul class="items">{li_items}</ul>'

        source_html = ""
        if source:
            source_html = f'<div class="source"><a href="{html.escape(source)}">{html.escape(source)}</a></div>'

        return f'<div class="section {css_class}">\n{heading_html}\n{body_html}\n{items_html}\n{source_html}\n</div>'
